# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称')),
                ('img', models.CharField(blank=True, max_length=200, verbose_name='图片链接地址')),
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='网址')),
                ('intro', models.TextField(default=None, max_length=2000, verbose_name='简介')),
                ('LOAD_TIME', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
            ],
        ),
    ]
