# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-17 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drama', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='id',
        ),
        migrations.AlterField(
            model_name='drama',
            name='img',
            field=models.CharField(blank=True, max_length=200, verbose_name='图片链接地址'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='intro',
            field=models.TextField(blank=True, max_length=2000, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='url',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='网址'),
        ),
    ]
