# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='分类'),
        ),
    ]
