# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-17 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drama', '0002_auto_20180817_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='LOAD_TIME',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='入库时间'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图片链接地址'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='intro',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名称'),
        ),
    ]
